version: '3.8'

services:
  db:
    container_name: db_teslo_shop
    image: postgres:13
    environment:
      POSTGRES_USER: teslo_user
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - ./postgres:/var/lib/postgresql/data